version: "1.4"
workspaces:
  - name: my-workspace
    slug: my-workspace
    id: 4f31596e-20f3-4166-8494-016e01c06c67
    created: 2026-03-09T19:07:06.220342+00:00
settings:
  id_prefix: TC
  id_counter: 0
  default_priority: medium
